In [1]:
import numpy as np
import pandas as pd

In [2]:
# Load the dataset using Pandas
df = pd.read_csv("student_performance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0
1,female,group E,some high school,free/reduced,none,61.0,47.0,99.0
2,female,group E,some high school,standard,none,76.0,62.0,100.0
3,male,group C,master's degree,free/reduced,none,30.0,95.0,94.0
4,male,group C,associate's degree,free/reduced,none,56.0,99.0,54.0
...,...,...,...,...,...,...,...,...
995,male,group B,bachelor's degree,standard,completed,59.0,84.0,75.0
996,male,group D,high school,standard,completed,78.0,62.0,66.0
997,male,group D,some college,free/reduced,completed,32.0,94.0,47.0
998,male,group A,some high school,standard,none,42.0,64.0,62.0
999,male,group A,associate's degree,standard,none,31.0,60.0,79.0

In [7]:
# Display the first and last 5 rows.

df.head(5)

# df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0
1,female,group E,some high school,free/reduced,none,61.0,47.0,99.0
2,female,group E,some high school,standard,none,76.0,62.0,100.0
3,male,group C,master's degree,free/reduced,none,30.0,95.0,94.0
4,male,group C,associate's degree,free/reduced,none,56.0,99.0,54.0

In [8]:
# Checking shape

df.shape

(1000, 8)

In [9]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [10]:
df.info

<bound method DataFrame.info of      gender race/ethnicity parental level of education         lunch  \
0    female        group C                some college  free/reduced
1    female        group E            some high school  free/reduced
2    female        group E            some high school      standard
3      male        group C             master's degree  free/reduced
4      male        group C          associate's degree  free/reduced
..      ...            ...                         ...           ...
995    male        group B           bachelor's degree      standard
996    male        group D                 high school      standard
997    male        group D                some college  free/reduced
998    male        group A            some high school      standard
999    male        group A          associate's degree      standard

    test preparation course  math score  reading score  writing score
0                 completed        69.0           73.0           49.0
1                      none        61.0           47.0           99.0
2                      none        76.0           62.0          100.0
3                      none        30.0           95.0           94.0
4                      none        56.0           99.0           54.0
..                      ...         ...            ...            ...
995               completed        59.0           84.0           75.0
996               completed        78.0           62.0           66.0
997               completed        32.0           94.0           47.0
998                    none        42.0           64.0           62.0
999                    none        31.0           60.0           79.0

[1000 rows x 8 columns]>

In [11]:
df.dtypes

gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                     float64
reading score                  float64
writing score                  float64
dtype: object

In [12]:
df.isnull().sum()

gender                         3
race/ethnicity                 3
parental level of education    4
lunch                          2
test preparation course        3
math score                     2
reading score                  3
writing score                  3
dtype: int64

In [15]:
df[['math score', 'reading score']]

     math score  reading score
0          69.0           73.0
1          61.0           47.0
2          76.0           62.0
3          30.0           95.0
4          56.0           99.0
..          ...            ...
995        59.0           84.0
996        78.0           62.0
997        32.0           94.0
998        42.0           64.0
999        31.0           60.0

[1000 rows x 2 columns]

In [16]:
df['gender'].value_counts()

gender
male      506
female    491
Name: count, dtype: int64

In [20]:
df['lunch'].unique()

df['test preparation course'].unique()

array(['completed', 'none', nan], dtype=object)

In [21]:
df[df['math score'] > 80]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
11,male,group E,bachelor's degree,standard,completed,86.0,85.0,74.0
13,female,group D,some college,free/reduced,none,81.0,90.0,64.0
15,female,group C,associate's degree,standard,completed,97.0,71.0,97.0
18,male,group C,some college,standard,none,82.0,69.0,81.0
21,male,group A,associate's degree,free/reduced,completed,90.0,31.0,69.0
...,...,...,...,...,...,...,...,...
969,female,group D,some college,standard,none,82.0,36.0,40.0
972,male,group D,some high school,free/reduced,completed,81.0,64.0,50.0
973,male,group E,master's degree,free/reduced,none,99.0,51.0,70.0
977,female,group A,some high school,standard,none,92.0,56.0,91.0
979,female,group B,some college,standard,completed,99.0,63.0,30.0

In [22]:
df[df['test preparation course'] == 'completed']

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0
6,female,group E,associate's degree,free/reduced,completed,47.0,43.0,34.0
7,male,group D,associate's degree,free/reduced,completed,43.0,66.0,57.0
10,female,group C,high school,free/reduced,completed,78.0,90.0,36.0
11,male,group E,bachelor's degree,standard,completed,86.0,85.0,74.0
...,...,...,...,...,...,...,...,...
992,male,group E,master's degree,standard,completed,51.0,68.0,51.0
994,male,group D,master's degree,standard,completed,69.0,56.0,93.0
995,male,group B,bachelor's degree,standard,completed,59.0,84.0,75.0
996,male,group D,high school,standard,completed,78.0,62.0,66.0
997,male,group D,some college,free/reduced,completed,32.0,94.0,47.0

In [ ]:
new_df = df[(df['gender'] == 'female') & (df['reading score'] > 70)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0
10,female,group C,high school,free/reduced,completed,78.0,90.0,36.0
13,female,group D,some college,free/reduced,none,81.0,90.0,64.0
15,female,group C,associate's degree,standard,completed,97.0,71.0,97.0
30,female,group C,bachelor's degree,standard,completed,61.0,100.0,43.0
...,...,...,...,...,...,...,...,...
966,female,group D,some college,free/reduced,none,44.0,78.0,86.0
967,female,group B,high school,standard,none,86.0,93.0,78.0
974,female,group C,high school,standard,none,52.0,100.0,33.0
983,female,group B,high school,standard,completed,58.0,83.0,54.0
990,female,group C,some high school,free/reduced,none,70.0,86.0,71.0

In [32]:
df['math score'].mean()

np.float64(62.5250501002004)

In [ ]:
df['reading score'].max()    #100
df['reading score'].min()    #25

np.float64(25.0)

In [39]:
df.groupby('race/ethnicity').size()
# df['race/ethnicity'].value_counts()

race/ethnicity
group A    212
group B    199
group C    206
group D    169
group E    211
dtype: int64

In [40]:
# df.groupby('race/ethnicity').size()
df['race/ethnicity'].value_counts()

race/ethnicity
group A    212
group E    211
group C    206
group B    199
group D    169
Name: count, dtype: int64

In [41]:
df.groupby('gender')['writing score'].mean()

gender
female    61.687755
male      62.051587
Name: writing score, dtype: float64

In [42]:
df.sort_values(by='math score', ascending=False).head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
642,female,group A,associate's degree,standard,completed,100.0,78.0,77.0
495,female,group A,bachelor's degree,standard,completed,100.0,48.0,81.0
878,male,group A,high school,free/reduced,none,100.0,88.0,96.0
126,male,group B,associate's degree,free/reduced,none,100.0,45.0,87.0
130,male,group B,some high school,standard,none,100.0,87.0,62.0
915,male,group A,high school,standard,completed,100.0,61.0,95.0
433,male,group E,associate's degree,free/reduced,completed,100.0,36.0,46.0
801,female,group A,some high school,standard,completed,100.0,29.0,69.0
827,male,group E,master's degree,standard,none,100.0,26.0,75.0
283,female,group C,some high school,free/reduced,none,100.0,28.0,57.0

In [ ]:
# Part 4: Beginner Friendly Tasks
# 1. Create a new column named total_score, which is the sum of math score,
#    reading score, and writing score.
# 2. Create a new column named average_score (total score divided by 3).
# 3. Add a column named result. A student passes if their average_score is 60 or above; otherwise, they fail.
#   (Hint: Use a conditional function or lambda expression).
# 4. Find the top 5 students based on their total_score.
# 5. Find the bottom 5 students based on their math score.

In [4]:
df['total_score'] = df['math score'] + df['reading score'] + df['writing score']
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0,191.0
1,female,group E,some high school,free/reduced,none,61.0,47.0,99.0,207.0
2,female,group E,some high school,standard,none,76.0,62.0,100.0,238.0
3,male,group C,master's degree,free/reduced,none,30.0,95.0,94.0,219.0
4,male,group C,associate's degree,free/reduced,none,56.0,99.0,54.0,209.0
...,...,...,...,...,...,...,...,...,...
995,male,group B,bachelor's degree,standard,completed,59.0,84.0,75.0,218.0
996,male,group D,high school,standard,completed,78.0,62.0,66.0,206.0
997,male,group D,some college,free/reduced,completed,32.0,94.0,47.0,173.0
998,male,group A,some high school,standard,none,42.0,64.0,62.0,168.0
999,male,group A,associate's degree,standard,none,31.0,60.0,79.0,170.0

In [5]:
df['average_score'] = df['total_score'].mean()
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,average_score
0,female,group C,some college,free/reduced,completed,69.0,73.0,49.0,191.0,187.300403
1,female,group E,some high school,free/reduced,none,61.0,47.0,99.0,207.0,187.300403
2,female,group E,some high school,standard,none,76.0,62.0,100.0,238.0,187.300403
3,male,group C,master's degree,free/reduced,none,30.0,95.0,94.0,219.0,187.300403
4,male,group C,associate's degree,free/reduced,none,56.0,99.0,54.0,209.0,187.300403
...,...,...,...,...,...,...,...,...,...,...
995,male,group B,bachelor's degree,standard,completed,59.0,84.0,75.0,218.0,187.300403
996,male,group D,high school,standard,completed,78.0,62.0,66.0,206.0,187.300403
997,male,group D,some college,free/reduced,completed,32.0,94.0,47.0,173.0,187.300403
998,male,group A,some high school,standard,none,42.0,64.0,62.0,168.0,187.300403
999,male,group A,associate's degree,standard,none,31.0,60.0,79.0,170.0,187.300403

In [6]:
df["result"] = np.where(
    df["average_score"] >= 60,
    "Pass",
    "Fail"
)

In [7]:
top_5 = df.sort_values(
    by="total_score",
    ascending=False
).head(5)

print(top_5)

     gender race/ethnicity parental level of education         lunch  \
278    male        group D          associate's degree      standard
878    male        group A                 high school  free/reduced
592    male        group B           bachelor's degree      standard
808    male        group B          associate's degree  free/reduced
89   female        group B          associate's degree      standard

    test preparation course  math score  reading score  writing score  \
278               completed        97.0           95.0          100.0
878                    none       100.0           88.0           96.0
592                    none        90.0           93.0           99.0
808               completed        91.0           92.0           98.0
89                     none        88.0           98.0           95.0

     total_score  average_score result
278        292.0     187.300403   Pass
878        284.0     187.300403   Pass
592        282.0     187.300403   Pass
808        281.0     187.300403   Pass
89         281.0     187.300403   Pass

In [9]:
bottom_5 = df.sort_values(
    by="math score",
    ascending=True
).head(5)

print(bottom_5)

     gender race/ethnicity parental level of education     lunch  \
36   female        group C             master's degree  standard
564  female        group A           bachelor's degree  standard
578  female        group C                 high school  standard
571  female        group E          associate's degree  standard
118  female        group B            some high school  standard

    test preparation course  math score  reading score  writing score  \
36                     none        25.0           56.0           29.0
564                    none        25.0           94.0           96.0
578                    none        25.0           42.0           51.0
571                    none        25.0           41.0           78.0
118                    none        25.0           73.0           45.0

     total_score  average_score result
36         110.0     187.300403   Pass
564        215.0     187.300403   Pass
578        118.0     187.300403   Pass
571        144.0     187.300403   Pass
118        143.0     187.300403   Pass